spring.application.name=emailSender
spring.mail.host=mail1.minskenergo.by
spring.mail.port=25
spring.mail.sender=asr@minskenergo.by
spring.mail.properties.mail.smtp.auth=true
spring.mail.password =Asr_2026
spring.mail.username =asr
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
resilience4j.circuitbreaker.instances.myService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.myService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.myService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.myService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.myService.permittedNumberOfCallsInHalfOpenState=3

